---
on:
  push:
    branches:
      - main
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@1232abb8968faf344409165de17cbf9e7f340fd8
      - uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: check

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@1232abb8968faf344409165de17cbf9e7f340fd8
      - uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fmt:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@1232abb8968faf344409165de17cbf9e7f340fd8
      - uses: actions-rs/clippy-check@9d09632661e31982c0be8af59aeb96b680641bc4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
