---
on:
  push:
    branches:
      - main
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

name: Continuous integration

jobs:
  rust_workflwos_ci:
    uses: hendrikmaus/rust-workflows/.github/workflows/ci.yaml@allow-reuse-of-ci-workflow
