---
name: CI

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  rust-workflows-ci:
    name: CI
    uses: hendrikmaus/rust-workflows/.github/workflows/ci.yaml@v0.9.0
